In [2]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame
import xgboost as xgb
from xgboost.sklearn import XGBClassifier
from sklearn import cross_validation, metrics
from sklearn.grid_search import GridSearchCV

import matplotlib.pylab as plt
%matplotlib inline
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 12, 4

In [3]:
train=pd.read_csv("train_all1.csv")

In [4]:
train.sitesetID.describe()

count    2.615000e+06
mean     2.469587e-01
std      4.488328e-01
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      2.000000e+00
Name: sitesetID, dtype: float64

In [5]:
vn_list=[ 'creativeID', 'userID',
       'positionID', 'connectionType', 'telecomsOperator', 'adID',
       'camgaignID', 'advertiserID', 'appID', 'appPlatform', 'age',
       'gender', 'education', 'marriageStatus', 'haveBaby', 'residence',
       'sitesetID', 'positionType', 'appCategory',  'hour',
       'residence2', 'creativeID_age', 'creativeID_gender',
       'creativeID_education', 'creativeID_marriageStatus',
       'creativeID_haveBaby', 'creativeID_advertiserID',
       'creativeID_residence', 'creativeID_hour', 'sitesetID_positionType',
    'creativeID_residence2', 'creativeID_positionID',
       'creativeID_telecomsOperator', 'creativeID_sitesetID',
       'connectionType_residence', 'connectionType_residence2',
       'adID_advertiserID', 'adID_age', 'adID_gender', 'adID_education',
       'adID_marriageStatus', 'adID_haveBaby', 'age_gender',
       'age_gender_edu', 'camgaignID_age', 'camgaignID_gender',
       'camgaignID_education', 'camgaignID_marriageStatus',
       'camgaignID_haveBaby', 'camgaignID_age_gender_edu',
       'adID_age_gender_edu', 'creativeID_age_gender_edu', 'appID_age',
       'appID_gender', 'appID_education', 'appID_marriageStatus',
       'appID_haveBaby', 'appID_age_gender_edu', 'appID_appPlatform',
       'appPlatform_age', 'appPlatform_edu', 'appPlatform_age_gender_edu',
       'positionID_age', 'positionID_gender', 'positionID_education',
       'positionID_marriageStatus', 'positionID_haveBaby',
       'positionID_age_gender_edu', 'sitesetID_age', 'sitesetID_gender',
       'sitesetID_education', 'sitesetID_marriageStatus',
       'sitesetID_haveBaby', 'sitesetID_age_gender_edu']

In [6]:
vn_list_std=pd.DataFrame({'str':range(0,74),'std':range(0,74),'mean':range(0,74),'25%':range(0,74),'50%':range(0,74),'75%':range(0,74)})

In [8]:
qqqq=train.copy()

In [9]:
for i in xrange(11,12):
    vn=vn_list[i]
    filter_t = np.logical_and(qqqq.day.values > 16, qqqq.day.values <= 29)
    qqqq['_key1'] = qqqq[vn].astype('category').values.codes
    df_yt = qqqq.ix[filter_t, ['_key1', 'label']]
    grp1 = df_yt.groupby(['_key1'])
    sum1 = grp1['label'].aggregate(np.sum).astype(float)
    cnt1 = grp1['label'].aggregate(np.size)
    vn_list_std.loc[i,'str']=vn
    vn_list_std.loc[i,'std']=(sum1/cnt1).describe()[2]
    vn_list_std.loc[i,'25%']=(sum1/cnt1).describe()[4]
    vn_list_std.loc[i,'50%']=(sum1/cnt1).describe()[5]
    vn_list_std.loc[i,'75%']=(sum1/cnt1).describe()[6]
    vn_list_std.loc[i,'mean']=(sum1/cnt1).describe()[1]

In [11]:
sum1

_key1
0     7890.0
1    48294.0
2    30770.0
Name: label, dtype: float64

In [12]:
cnt1

_key1
0      27517
1    1269763
2    1084337
Name: label, dtype: int64

In [18]:
sum1/cnt1

_key1
0    0.286732
1    0.038034
2    0.028377
Name: label, dtype: float64

In [19]:
np.std(sum1/cnt1)

0.11957855242208329

In [10]:
vn_list_std.sort('std')

          25%        50%        75%       mean        std     str
0    0.000000   0.000000   0.000000   0.000000   0.000000       0
1    1.000000   1.000000   1.000000   1.000000   1.000000       1
2    2.000000   2.000000   2.000000   2.000000   2.000000       2
3    3.000000   3.000000   3.000000   3.000000   3.000000       3
4    4.000000   4.000000   4.000000   4.000000   4.000000       4
5    5.000000   5.000000   5.000000   5.000000   5.000000       5
6    6.000000   6.000000   6.000000   6.000000   6.000000       6
7    7.000000   7.000000   7.000000   7.000000   7.000000       7
8    8.000000   8.000000   8.000000   8.000000   8.000000       8
9    9.000000   9.000000   9.000000   9.000000   9.000000       9
10  10.000000  10.000000  10.000000  10.000000  10.000000      10
11   0.033205   0.038034   0.162383   0.117714   0.146453  gender
12  12.000000  12.000000  12.000000  12.000000  12.000000      12
13  13.000000  13.000000  13.000000  13.000000  13.000000      13
14  14.000000  14.000000  14.000000  14.000000  14.000000      14
15  15.000000  15.000000  15.000000  15.000000  15.000000      15
16  16.000000  16.000000  16.000000  16.000000  16.000000      16
17  17.000000  17.000000  17.000000  17.000000  17.000000      17
18  18.000000  18.000000  18.000000  18.000000  18.000000      18
19  19.000000  19.000000  19.000000  19.000000  19.000000      19
20  20.000000  20.000000  20.000000  20.000000  20.000000      20
21  21.000000  21.000000  21.000000  21.000000  21.000000      21
22  22.000000  22.000000  22.000000  22.000000  22.000000      22
23  23.000000  23.000000  23.000000  23.000000  23.000000      23
24  24.000000  24.000000  24.000000  24.000000  24.000000      24
25  25.000000  25.000000  25.000000  25.000000  25.000000      25
26  26.000000  26.000000  26.000000  26.000000  26.000000      26
27  27.000000  27.000000  27.000000  27.000000  27.000000      27
28  28.000000  28.000000  28.000000  28.000000  28.000000      28
29  29.000000  29.000000  29.000000  29.000000  29.000000      29
..        ...        ...        ...        ...        ...     ...
44  44.000000  44.000000  44.000000  44.000000  44.000000      44
45  45.000000  45.000000  45.000000  45.000000  45.000000      45
46  46.000000  46.000000  46.000000  46.000000  46.000000      46
47  47.000000  47.000000  47.000000  47.000000  47.000000      47
48  48.000000  48.000000  48.000000  48.000000  48.000000      48
49  49.000000  49.000000  49.000000  49.000000  49.000000      49
50  50.000000  50.000000  50.000000  50.000000  50.000000      50
51  51.000000  51.000000  51.000000  51.000000  51.000000      51
52  52.000000  52.000000  52.000000  52.000000  52.000000      52
53  53.000000  53.000000  53.000000  53.000000  53.000000      53
54  54.000000  54.000000  54.000000  54.000000  54.000000      54
55  55.000000  55.000000  55.000000  55.000000  55.000000      55
56  56.000000  56.000000  56.000000  56.000000  56.000000      56
57  57.000000  57.000000  57.000000  57.000000  57.000000      57
58  58.000000  58.000000  58.000000  58.000000  58.000000      58
59  59.000000  59.000000  59.000000  59.000000  59.000000      59
60  60.000000  60.000000  60.000000  60.000000  60.000000      60
61  61.000000  61.000000  61.000000  61.000000  61.000000      61
62  62.000000  62.000000  62.000000  62.000000  62.000000      62
63  63.000000  63.000000  63.000000  63.000000  63.000000      63
64  64.000000  64.000000  64.000000  64.000000  64.000000      64
65  65.000000  65.000000  65.000000  65.000000  65.000000      65
66  66.000000  66.000000  66.000000  66.000000  66.000000      66
67  67.000000  67.000000  67.000000  67.000000  67.000000      67
68  68.000000  68.000000  68.000000  68.000000  68.000000      68
69  69.000000  69.000000  69.000000  69.000000  69.000000      69
70  70.000000  70.000000  70.000000  70.000000  70.000000      70
71  71.000000  71.000000  71.000000  71.000000  71.000000      71
72  72.000000  72.000000  72.000000  72.000000  72.000000      72
73  73.000000  73.000000  73.000000  73.000000  73.000000      73

[74 rows x 6 columns]

In [ ]:
def expctr(df,vn):
    vn_key = vn
    day1 = 16
    for day_v in xrange(17,30):
        filter_t = np.logical_and(df.day.values > day1, df.day.values <= day_v)
        t1 = df.ix[filter_t, :]
        filter_t2 = np.logical_and(t1.day.values != day_v, t1.day.values < 31)
        df['_key1'] = df[vn].astype('category').values.codes
        df_yt = df.ix[filter_t2, ['_key1', 'label']]
        grp1 = df_yt.groupby(['_key1'])
        sum1 = grp1['label'].aggregate(np.sum)
        cnt1 = grp1['label'].aggregate(np.size)
        v_codes = df.ix[df.day.values == day_v, '_key1']
        _sum = sum1[v_codes].values.astype(float)
        _cnt = cnt1[v_codes].values
        df.loc[df.day.values == day_v, 'cnttv_'+vn_key]=np.divide(_sum,_cnt)

del train['_key1']

In [111]:
for vn in vn_list:
     expctr(train,vn)

MemoryError:

In [ ]:
del train['_key1']